In [1]:
import numpy as np

In [26]:
A = np.array([[1,2,-1],
              [1,1,-3]
             ])

In [27]:
A

array([[ 1,  2, -1],
       [ 1,  1, -3]])

In [28]:
B = np.array([[3,2,-2],
              [-1,2,1]
             ])

In [29]:
B

array([[ 3,  2, -2],
       [-1,  2,  1]])

In [30]:
C = A+B

In [31]:
C

array([[ 4,  4, -3],
       [ 0,  3, -2]])

In [32]:
C[0,2]

-3

In [33]:
D =np.array([[1,2,-1],
             [1,1,-3]
            ])

In [34]:
D

array([[ 1,  2, -1],
       [ 1,  1, -3]])

In [41]:
E = np.array([[3],[1],[2]])

In [59]:
E

array([[3],
       [1],
       [2]])

In [60]:
D.dot(E)

array([[ 3],
       [-2]])

In [43]:
G =np.array([[1,2,-1],
      [1,1,-3]
     ])

In [44]:
G

array([[ 1,  2, -1],
       [ 1,  1, -3]])

In [46]:
H = np.array([[3,2],[1,1],[2,-1]])

In [47]:
H

array([[ 3,  2],
       [ 1,  1],
       [ 2, -1]])

In [62]:
print(np.dot(G,H))

[[ 3  5]
 [-2  6]]
