In [1]:
import numpy # numpy 불러오기

In [2]:
array1 = numpy.array([2,3,5,6,11,13,17,19])   # numpy array 함수 사용

In [3]:
array1

array([ 2,  3,  5,  6, 11, 13, 17, 19])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape

(8,)

In [17]:
array2 = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
type(array2)

numpy.ndarray

In [20]:
array2.shape

(3, 4)

In [21]:
array2.size

12

In [22]:
import numpy

array1 = numpy.full(6,0)
array2 = numpy.random.random(6)

In [23]:
import numpy as np

array1 = np.full(6,0)
array2 = np.random.random(6)

In [24]:
array1

array([0, 0, 0, 0, 0, 0])

In [25]:
array2

array([0.98977883, 0.26786951, 0.70816326, 0.70053776, 0.80808241,
       0.13513649])