In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
array1[0]                        #0번 째 인덱스 값 불러오기 (인덱싱)

1

In [6]:
array1[5]

6

In [7]:
array1[-1]

10

In [8]:
array1[[1,3,4]]           #python 리스트로 인덱스 값 불러오기

array([2, 4, 5])

In [9]:
array2 = np.array([2,1,3])          

In [10]:
array1[array2]                 #numpy array 로 인덱스 값 불러오기

array([3, 2, 4])

In [11]:
array1 [2:7]              #슬라이싱 2번 인덱스부터 7번 인덱스 까지 불러오기

array([3, 4, 5, 6, 7])

In [12]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
array1[2:6:3]

array([3, 6])