In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
titanic = sns.load_dataset('titanic')

In [3]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
grJob = titanic.groupby("sex")
print(grJob["survived"].count())

sex
female    314
male      577
Name: survived, dtype: int64


In [5]:
c = titanic[titanic['survived']== 1]
a = c.groupby('sex')
print(a['survived'].count())

sex
female    233
male      109
Name: survived, dtype: int64


In [6]:
print(titanic['age'].max())
print(titanic['age'].min())

80.0
0.42


In [7]:
a = titanic['survived'].unique()
print(a)
b = titanic['pclass'].unique()
print(b)
c = titanic['sex'].unique()
print(c)
d = titanic['age'].unique()
print(a)
e = titanic['sibsp'].unique()
print(e)
f = titanic['parch'].unique()
print(f)
g = titanic['fare'].unique()
print(g)
h = titanic['embarked'].unique()
print(h)
i = titanic['class'].unique()
print(i)
j = titanic['who'].unique()
print(j)
k = titanic['adult_male'].unique()
print(k)
l = titanic['deck'].unique()
print(l)
m = titanic['embark_town'].unique()
print(m)
n = titanic['alive'].unique()
print(n)
o = titanic['alone'].unique()
print(o)

[0 1]
[3 1 2]
['male' 'female']
[0 1]
[1 0 3 4 2 5 8]
[0 1 2 5 3 4 6]
[  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55    31.275    7.8542  16.      29.125
  13.      18.       7.225   26.       8.0292  35.5     31.3875 263.
   7.8792   7.8958  27.7208 146.5208   7.75    10.5     82.1708  52.
   7.2292  11.2417   9.475   21.      41.5792  15.5     21.6792  17.8
  39.6875   7.8     76.7292  61.9792  27.75    46.9     80.      83.475
  27.9     15.2458   8.1583   8.6625  73.5     14.4542  56.4958   7.65
  29.      12.475    9.       9.5      7.7875  47.1     15.85    34.375
  61.175   20.575   34.6542  63.3583  23.      77.2875   8.6542   7.775
  24.15     9.825   14.4583 247.5208   7.1417  22.3583   6.975    7.05
  14.5     15.0458  26.2833   9.2167  79.2      6.75    11.5     36.75
   7.7958  12.525   66.6      7.3125  61.3792   7.7333  69.55    16.1
  15.75    20.525   55.      25.925   33.5     30.6958  25.4667  28.7125
   0. 

In [8]:
age = pd.cut(titanic['age'],[0,10,20,30,40,50,60,70,80])
titanic.pivot_table('survived',['sex',age], 'class') 

class               First    Second     Third
sex    age                                   
female (0, 10]   0.000000  1.000000  0.500000
       (10, 20]  1.000000  1.000000  0.520000
       (20, 30]  0.952381  0.892857  0.500000
       (30, 40]  1.000000  0.941176  0.428571
       (40, 50]  0.923077  0.900000  0.000000
       (50, 60]  1.000000  0.666667       NaN
       (60, 70]  1.000000       NaN  1.000000
male   (0, 10]   1.000000  1.000000  0.363636
       (10, 20]  0.400000  0.100000  0.129630
       (20, 30]  0.473684  0.000000  0.144330
       (30, 40]  0.520000  0.115385  0.142857
       (40, 50]  0.375000  0.111111  0.090909
       (50, 60]  0.285714  0.000000  0.000000
       (60, 70]  0.000000  0.333333  0.000000
       (70, 80]  0.333333       NaN  0.000000

In [9]:
import pandas as pd 
import seaborn as sns 

titanic = sns.load_dataset('titanic')

titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')